// Converts the output of tools/equity.c into js/data/equity.js.
//
//   gcc -O3 -march=native -fopenmp -o equity tools/equity.c
//   ./equity 1000000 > equity.txt
//   node tools/build-equity.mjs equity.txt
//
// The upper triangle (row < col) is stored as integers in units of 0.01%.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const src = process.argv[2];
if (!src) {
  console.error('usage: node tools/build-equity.mjs <equity.txt>');
  process.exit(1);
}

const rows = readFileSync(src, 'utf8').trim().split('\n').map((l) => l.trim().split(/\s+/).map(Number));
if (rows.length !== 169 || rows.some((r) => r.length !== 169)) throw new Error('expected a 169x169 matrix');

const upper = [];
for (let a = 0; a < 169; a++) for (let b = a + 1; b < 169; b++) upper.push(Math.round(rows[a][b] * 10000));

const lines = [];
for (let i = 0; i < upper.length; i += 40) lines.push('    ' + upper.slice(i, i + 40).join(','));

const out = `/*
 * Preflop all-in equity of every hand class against every other class,
 * generated by tools/equity.c (Monte Carlo, 1M boards per matchup; standard
 * error under 0.05%). Do not edit by hand.
 *
 * Upper triangle of a 169x169 matrix in grid order, row < col, in units of
 * 0.01%. Decode with GTO.core.decodeEquity().
 */
(function (root) {
  root.GTO = root.GTO || {};
  root.GTO.equityUpper = [
${lines.join(',\n')}
  ];
})(typeof window !== 'undefined' ? window : globalThis);
`;

const dest = fileURLToPath(new URL('../js/data/equity.js', import.meta.url));
writeFileSync(dest, out);
console.log(`wrote ${dest} (${upper.length} matchups, ${(out.length / 1024).toFixed(0)} KB)`);
